# from shoelace.pianoroll_vq.vector_quantize_pytorch.vector_quantize_pytorch import VectorQuantize
# from shoelace.pianoroll_vq.vector_quantize_pytorch.residual_vq import ResidualVQ, GroupedResidualVQ
# from shoelace.pianoroll_vq.vector_quantize_pytorch.random_projection_quantizer import RandomProjectionQuantizer
# from shoelace.pianoroll_vq.vector_quantize_pytorch.finite_scalar_quantization import FSQ
# from shoelace.pianoroll_vq.vector_quantize_pytorch.lookup_free_quantization import LFQ
# from shoelace.pianoroll_vq.vector_quantize_pytorch.residual_lfq import ResidualLFQ, GroupedResidualLFQ
# from shoelace.pianoroll_vq.vector_quantize_pytorch.residual_fsq import ResidualFSQ, GroupedResidualFSQ
# from shoelace.pianoroll_vq.vector_quantize_pytorch.latent_quantization import LatentQuantize
