lr=1e-4
exp=exp
batch_size=4
e=15
n_prompts=5
mask_type=bi_mask
model_type=bi_di
exp_dir=bi_direct_medium_n_prompts_${model_type}_${n_prompts}

CUDA_VISIBLE_DEVICES=0 python -m shoelace.actual_shoelace.train_single_gpu \
      --learning_rate=$lr \
      --experiment_folder=$exp \
      --batch_size=$batch_size \
      --epoch=$e \
      --exp_name=$exp_dir \
      --duration=15.36 \
      --mask_type=${mask_type} \
      --n_prompts=${n_prompts} \
      --model_type=${model_type}
